# Generated by Django 4.0.1 on 2022-01-25 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('image', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('image', models.CharField(max_length=500)),
                ('type', models.CharField(max_length=126)),
                ('price', models.PositiveIntegerField(default=0)),
                ('rating', models.CharField(max_length=126)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='situater', to='situater.location')),
            ],
        ),
    ]
