# Generated by Django 4.0.1 on 2022-01-28 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('situater', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attraction',
            name='image',
            field=models.CharField(max_length=800),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attractions', to='situater.location'),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='name',
            field=models.CharField(max_length=800),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='rating',
            field=models.CharField(max_length=800),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='type',
            field=models.CharField(max_length=800),
        ),
        migrations.AlterField(
            model_name='location',
            name='image',
            field=models.CharField(max_length=800),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=800),
        ),
    ]
