# Generated by Django 4.0.1 on 2022-01-29 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('situater', '0002_alter_attraction_image_alter_attraction_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attraction',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attractions', to='situater.location'),
        ),
    ]
